#!/usr/bin/perl
use strict;
use warnings;

my $pid = fork();
if($pid == 0){
        sleep(1);
        `sudo apache2ctl -k graceful`;
}
open STDOUT, '>/dev/null';
open STDIN, '>/dev/null';
open STDERR, '>/dev/null';

